sudo: required
services:
  - docker

before_install:
  - docker build -t pratik151/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true pratik151/docker-react-app npm run test -- --coverage