sudo: required
services:
  - docker

before_install:
  - docker build -t pratik151/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true pratik151/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sample-docker"
  env: "Sampledocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-566716581275"
  bucket_path: "sample-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
